= Apiman Gateway Production Guide

{{ start }}++++
{% method %}
== Setting the API Gateway Public Endpoint

An important step is to let the API Gateway know what its public endpoint is.  This is important because the API Manager will sometimes ask the Gateway to report on the Managed Endpoint for a published API.

{% sample lang="Vert.x" %}
To set the public endpoint of the API Gateway, add the following to `conf.json`:

```json
{
  "publicEndpoint": "https://api-gateway-host.org:8443"// <1>
}
```
<1> You can also append a path, etc. This is useful if you are behind a proxy and need to report a specific endpoint.

{% sample lang="Servlet" %}
To set the public URL/endpoint of the API Gateway, add the following to `apiman.properties`:

    apiman-gateway.public-endpoint=https://api-gateway-host.org:8443/apiman-gateway/

{% common %}
WARNING: Please make sure to use your appropriate values for the host and port.

{% endmethod %}
{{ end }}++++

{{ start }}++++
{% method %}
== Pointing the API Gateway to a Remote Elasticsearch

The API Gateway uses Elasticsearch in a number of ways, including:

* Storing configuration information
* Managing shared state across a cluster
* Storing metrics to share with the API Manager  (analytics)

In order to configure the gateway properly, you will need to configure the location of the Elasticsearch instance.

{% sample lang="Vert.x" %}
To do this, modify these properties in the `conf.json` file **for each ES component**. For example:

```json
"registry": {
  "class": "io.apiman.gateway.engine.es.ESRegistry",
  "config": {
    "client": {
      "type": "jest",
      "cluster-name": "elasticsearch",
      "host": "localhost", // <1>
      "port": "9200",
      "initialize": true
    }
  }
}
```
<1> You could use Environment Variables or System Properties such as `${ES_HOST}` `${ES_PORT}`.

{% sample lang="Servlet" %}
To do this, modify these properties in the `apiman.properties` file:

    apiman.es.protocol=http
    apiman.es.host=es.myorg.com
    apiman.es.port=9200
    apiman.es.username=es_admin
    apiman.es.password=es_admin_password

{% common %}
TIP: You will need to replace the values above with those appropriate for your installation of Elasticsearch.

{% endmethod %}
{{ end }}++++

== Pointing the API Gateway to a Remote Keycloak

Refer to the Installation section on link:https://apiman.gitbooks.io/apiman-installation-guide/installation-guide/gateway/security.html#_setup[configuring a Remote Keycloak instance]. Be sure to select your implementation by clicking on the *Vert.x* or *Servlet* tabs at the top right.
