= Vert.x Production Guide

Simply download the Vert.x quickstart and make some modifications to `conf.json`; you should be up and running in short order.

TIP: The _Gateway_ is Vert.x, but you will still run the _Manager_ aspects using WildFly/EAP.

== Configuring Keycloak Authentication for the Gateway API

* Log into your Keycloak instance.
* Navigate to `Clients` -> `apiman-gateway-api`
* In `Settings`, change the `Access Type` to `confidential`. Click `Save`.
* In `Installation` select `Keycloak OIDC JSON` and copy the produced JSON.
* Paste the JSON into the `config` section of `auth`.

```json
"auth": {
  "type": "keycloak",
  "config": {
    "flowType": "PASSWORD", // <1>
    "requiredRole": "realm:apipublisher", // <2>
    // Paste your Keycloak config here.
    "realm": "apiman",
    "realm-public-key": "MIIBIjANBgkqhkiG9w0BAQ...", // <3>
    "auth-server-url": "http://localhost:8080/auth", // <4>
    "ssl-required": "none",
    "public-client": true,
    "resource": "apiman-gateway-api",
    "credentials": {
      "secret": "217b725d-7790-47a7-a3fc-5cf31f92a8db"
    }
  }
}
```
<1> The OAuth2 flow type. Leave intact.
<2> The required role to be allowed to publish. You probably do not need to change this.
<3> Snipped for readability.
<4> You may need to change this if your Keycloak server does not report the needed URL.
